# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jezen.ui'
#
# Created: Sat Aug  1 07:54:20 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1203, 833)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.mainSplitter = QtGui.QSplitter(self.centralwidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName(_fromUtf8("mainSplitter"))
        self.notebookSplitter = QtGui.QSplitter(self.mainSplitter)
        self.notebookSplitter.setOrientation(QtCore.Qt.Vertical)
        self.notebookSplitter.setObjectName(_fromUtf8("notebookSplitter"))
        self.notebookGroupBox = QtGui.QGroupBox(self.notebookSplitter)
        self.notebookGroupBox.setObjectName(_fromUtf8("notebookGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.notebookGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.notebookMVC = NotebookMVC(self.notebookGroupBox)
        self.notebookMVC.setObjectName(_fromUtf8("notebookMVC"))
        self.verticalLayout.addWidget(self.notebookMVC)
        self.keywordGroupBox = QtGui.QGroupBox(self.notebookSplitter)
        self.keywordGroupBox.setObjectName(_fromUtf8("keywordGroupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.keywordGroupBox)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.keywordsListView = QtGui.QListView(self.keywordGroupBox)
        self.keywordsListView.setObjectName(_fromUtf8("keywordsListView"))
        self.verticalLayout_3.addWidget(self.keywordsListView)
        self.notesGroupBox = QtGui.QGroupBox(self.mainSplitter)
        self.notesGroupBox.setObjectName(_fromUtf8("notesGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.notesGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.noteMVC = NoteMVC(self.notesGroupBox)
        self.noteMVC.setObjectName(_fromUtf8("noteMVC"))
        self.verticalLayout_2.addWidget(self.noteMVC)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.sortbyLabel = QtGui.QLabel(self.notesGroupBox)
        self.sortbyLabel.setObjectName(_fromUtf8("sortbyLabel"))
        self.horizontalLayout_4.addWidget(self.sortbyLabel)
        self.sortbyCcomboBox = QtGui.QComboBox(self.notesGroupBox)
        self.sortbyCcomboBox.setObjectName(_fromUtf8("sortbyCcomboBox"))
        self.horizontalLayout_4.addWidget(self.sortbyCcomboBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.tabWidget = QtGui.QTabWidget(self.mainSplitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.viewTab = QtGui.QWidget()
        self.viewTab.setObjectName(_fromUtf8("viewTab"))
        self.tabWidget.addTab(self.viewTab, _fromUtf8(""))
        self.editTab = QtGui.QWidget()
        self.editTab.setObjectName(_fromUtf8("editTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.editTab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.editSplitter = QtGui.QSplitter(self.editTab)
        self.editSplitter.setOrientation(QtCore.Qt.Vertical)
        self.editSplitter.setObjectName(_fromUtf8("editSplitter"))
        self.keywordEditGroupBox = QtGui.QGroupBox(self.editSplitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keywordEditGroupBox.sizePolicy().hasHeightForWidth())
        self.keywordEditGroupBox.setSizePolicy(sizePolicy)
        self.keywordEditGroupBox.setMaximumSize(QtCore.QSize(16777215, 64))
        self.keywordEditGroupBox.setObjectName(_fromUtf8("keywordEditGroupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.keywordEditGroupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.keywordLineEdit = QtGui.QLineEdit(self.keywordEditGroupBox)
        self.keywordLineEdit.setObjectName(_fromUtf8("keywordLineEdit"))
        self.verticalLayout_6.addWidget(self.keywordLineEdit)
        self.markdownGroupBox = QtGui.QGroupBox(self.editSplitter)
        self.markdownGroupBox.setObjectName(_fromUtf8("markdownGroupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.markdownGroupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.noteTextEdit = QtGui.QTextEdit(self.markdownGroupBox)
        self.noteTextEdit.setObjectName(_fromUtf8("noteTextEdit"))
        self.verticalLayout_5.addWidget(self.noteTextEdit)
        self.attachmentsGroupBox = QtGui.QGroupBox(self.editSplitter)
        self.attachmentsGroupBox.setObjectName(_fromUtf8("attachmentsGroupBox"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.attachmentsGroupBox)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.attachColumnView = QtGui.QColumnView(self.attachmentsGroupBox)
        self.attachColumnView.setObjectName(_fromUtf8("attachColumnView"))
        self.verticalLayout_4.addWidget(self.attachColumnView)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.attachUploadButton = QtGui.QPushButton(self.attachmentsGroupBox)
        self.attachUploadButton.setObjectName(_fromUtf8("attachUploadButton"))
        self.horizontalLayout.addWidget(self.attachUploadButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_7.addWidget(self.editSplitter)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.saveButton = QtGui.QPushButton(self.editTab)
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.editTab, _fromUtf8(""))
        self.horizontalLayout_3.addWidget(self.mainSplitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1203, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Notebook = QtGui.QAction(MainWindow)
        self.actionNew_Notebook.setObjectName(_fromUtf8("actionNew_Notebook"))
        self.actionSet_Directory = QtGui.QAction(MainWindow)
        self.actionSet_Directory.setObjectName(_fromUtf8("actionSet_Directory"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionNew_Note = QtGui.QAction(MainWindow)
        self.actionNew_Note.setObjectName(_fromUtf8("actionNew_Note"))
        self.actionPrint_Note = QtGui.QAction(MainWindow)
        self.actionPrint_Note.setObjectName(_fromUtf8("actionPrint_Note"))
        self.menuFile.addAction(self.actionNew_Note)
        self.menuFile.addAction(self.actionNew_Notebook)
        self.menuFile.addAction(self.actionPrint_Note)
        self.menuFile.addAction(self.actionSet_Directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Jezen", None))
        self.notebookGroupBox.setTitle(_translate("MainWindow", "Note Books", None))
        self.keywordGroupBox.setTitle(_translate("MainWindow", "Key Words", None))
        self.notesGroupBox.setTitle(_translate("MainWindow", "Notes", None))
        self.sortbyLabel.setText(_translate("MainWindow", "Sort By:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.viewTab), _translate("MainWindow", "View", None))
        self.keywordEditGroupBox.setTitle(_translate("MainWindow", "Keywords", None))
        self.markdownGroupBox.setTitle(_translate("MainWindow", "Markdown", None))
        self.attachmentsGroupBox.setTitle(_translate("MainWindow", "Attachments", None))
        self.attachUploadButton.setText(_translate("MainWindow", "Upload", None))
        self.saveButton.setText(_translate("MainWindow", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.editTab), _translate("MainWindow", "Edit", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionNew_Notebook.setText(_translate("MainWindow", "New Notebook", None))
        self.actionSet_Directory.setText(_translate("MainWindow", "Set Directory", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionNew_Note.setText(_translate("MainWindow", "New Note", None))
        self.actionPrint_Note.setText(_translate("MainWindow", "Print Note", None))

from note import NoteMVC
from notebook import NotebookMVC
